In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
# gets the basics info about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [4]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [5]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [6]:
df.shape

(10683, 11)

In [7]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [8]:
# Feature Engineering
df['Date']=df["Date_of_Journey"].str.split('/').str[0]
df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df['Year']=df["Date_of_Journey"].str.split('/').str[2]

In [9]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,01,03,2019

In [10]:
df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [12]:
# Drop date of Journey
df.drop('Date_of_Journey',axis=1,inplace=True)

In [13]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [14]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(" ")[0])

In [15]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [15]:
df['Arrival_Hour']=df['Arrival_Time'].str.split(":").str[0]
df['Arrival_min']=df['Arrival_Time'].str.split(":").str[1]

In [16]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15

In [17]:
df['Arrival_Hour']=df['Arrival_Hour'].astype(int)
df['Arrival_min']=df['Arrival_Hour'].astype(int)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
dtypes: int64(4), object(9)
memory usage: 1.1+ MB

In [17]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
dtypes: int64(4), object(9)
memory usage: 1.1+ MB

In [20]:
df['Departure_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Departure_Min']=df['Dep_Time'].str.split(':').str[1]

In [22]:
df['Departure_Hour']=df['Departure_Hour'].astype(int)
df['Departure_Min']=df['Departure_Min'].astype(int)

In [23]:
df.drop('Dep_Time',axis=1,inplace=True)

In [24]:
df.head(2)

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Departure_Hour,Departure_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50

In [25]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [26]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Departure_Hour,Departure_Min
9039,Air India,Delhi,Cochin,NaN,09:25,23h 40m,NaN,No info,7480,6,5,2019,9,45

In [27]:
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '1 stop':1, '2 stop':2, '3 stops':3, '4 stops':4,np.nan:1})

In [28]:
df.head()

,Airline,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Departure_Hour,Departure_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10,2h 50m,0.0,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,NaN,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,04:25,19h,NaN,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1.0,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1.0,No info,13302,1,3,2019,16,50

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Arrival_Time     10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      9163 non-null   float64
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Departure_Hour   10683 non-null  int64
 13  Departure_Min    10683 non-null  int64
dtypes: float64(1), int64(6), object(7)
memory usage: 1.1+ MB

In [32]:
df['Total_Stops'] = df['Total_Stops'].fillna(0).astype(float)

In [33]:
df.drop('Total_Stops',axis=1,inplace=True)

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Arrival_Time,Duration,Additional_Info,Price,Date,Month,Year,Departure_Hour,Departure_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,01:10,2h 50m,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,No info,7662,1,5,2019,5,50

In [51]:
df.drop('Route',axis=1,inplace=True)

In [52]:
df.head(2)

,Airline,Source,Destination,Arrival_Time,Duration,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_min,Departure_Hour,Departure_Min,Total_stops
0,IndiGo,Banglore,New Delhi,01:10,2h 50m,No info,3897,24,3,2019,1,1,22,20,0
1,Air India,Kolkata,Banglore,13:15,7h 25m,No info,7662,1,5,2019,13,13,5,50,0

In [ ]:
df['Duration']=df['D'].str.split('h').str[0]
df['Duration'].str.split(' ').str[1].str.split('m').str[1]

0
1
2        NaN
3
4
        ...
10678
10679
10680    NaN
10681
10682
Name: Duration, Length: 10683, dtype: object

In [ ]:
df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration'].str.split(' ').str[1].str.split('m').str[1]

In [54]:
df.head(2)

,Airline,Source,Destination,Arrival_Time,Duration,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_min,Departure_Hour,Departure_Min,Total_stops
0,IndiGo,Banglore,New Delhi,01:10,2h 50m,No info,3897,24,3,2019,1,1,22,20,0
1,Air India,Kolkata,Banglore,13:15,7h 25m,No info,7662,1,5,2019,13,13,5,50,0

In [55]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [56]:
df['Source'].unique()

array(['Banglore', 'Kolkata', 'Delhi', 'Chennai', 'Mumbai'], dtype=object)

In [57]:
from sklearn.preprocessing import OneHotEncoder

In [58]:
encoder=OneHotEncoder()

In [59]:
encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [60]:
df.head()

,Airline,Source,Destination,Arrival_Time,Duration,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_min,Departure_Hour,Departure_Min,Total_stops
0,IndiGo,Banglore,New Delhi,01:10,2h 50m,No info,3897,24,3,2019,1,1,22,20,0
1,Air India,Kolkata,Banglore,13:15,7h 25m,No info,7662,1,5,2019,13,13,5,50,0
2,Jet Airways,Delhi,Cochin,04:25,19h,No info,13882,9,6,2019,4,4,9,25,0
3,IndiGo,Kolkata,Banglore,23:30,5h 25m,No info,6218,12,5,2019,23,23,18,5,1
4,IndiGo,Banglore,New Delhi,21:35,4h 45m,No info,13302,1,3,2019,21,21,16,50,1

In [61]:
encoded_df = pd.DataFrame(
    encoder.fit_transform(df[['Airline', 'Source', 'Destination']]).toarray(),
    columns=encoder.get_feature_names_out()
)

df = pd.concat([df, encoded_df], axis=1)

In [62]:
df.head()

,Airline,Source,Destination,Arrival_Time,Duration,Additional_Info,Price,Date,Month,Year,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,IndiGo,Banglore,New Delhi,01:10,2h 50m,No info,3897,24,3,2019,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Air India,Kolkata,Banglore,13:15,7h 25m,No info,7662,1,5,2019,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,Jet Airways,Delhi,Cochin,04:25,19h,No info,13882,9,6,2019,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,IndiGo,Kolkata,Banglore,23:30,5h 25m,No info,6218,12,5,2019,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,IndiGo,Banglore,New Delhi,21:35,4h 45m,No info,13302,1,3,2019,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 38 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Airline                                    10683 non-null  object
 1   Source                                     10683 non-null  object
 2   Destination                                10683 non-null  object
 3   Arrival_Time                               10683 non-null  object
 4   Duration                                   10683 non-null  object
 5   Additional_Info                            10683 non-null  object
 6   Price                                      10683 non-null  int64
 7   Date                                       10683 non-null  int32
 8   Month                                      10683 non-null  int32
 9   Year                                       10683 non-null  int32
 10  Arrival_Hour                               10683 non-null  int32
 11  Arrival_min                                10683 non-null  int32
 12  Departure_Hour                             10683 non-null  int32
 13  Departure_Min                              10683 non-null  int32
 14  Total_stops                                10683 non-null  int32
 15  Airline_Air Asia                           10683 non-null  float64
 16  Airline_Air India                          10683 non-null  float64
 17  Airline_GoAir                              10683 non-null  float64
 18  Airline_IndiGo                             10683 non-null  float64
 19  Airline_Jet Airways                        10683 non-null  float64
 20  Airline_Jet Airways Business               10683 non-null  float64
 21  Airline_Multiple carriers                  10683 non-null  float64
 22  Airline_Multiple carriers Premium economy  10683 non-null  float64
 23  Airline_SpiceJet                           10683 non-null  float64
 24  Airline_Trujet                             10683 non-null  float64
 25  Airline_Vistara                            10683 non-null  float64
 26  Airline_Vistara Premium economy            10683 non-null  float64
 27  Source_Banglore                            10683 non-null  float64
 28  Source_Chennai                             10683 non-null  float64
 29  Source_Delhi                               10683 non-null  float64
 30  Source_Kolkata                             10683 non-null  float64
 31  Source_Mumbai                              10683 non-null  float64
 32  Destination_Banglore                       10683 non-null  float64
 33  Destination_Cochin                         10683 non-null  float64
 34  Destination_Delhi                          10683 non-null  float64
 35  Destination_Hyderabad                      10683 non-null  float64
 36  Destination_Kolkata                        10683 non-null  float64
 37  Destination_New Delhi                      10683 non-null  float64
dtypes: float64(23), int32(8), int64(1), object(6)
memory usage: 2.8+ MB